---
title: "X-G-Boost"
author: "Gabriele Minniti"
date: "4/5/2018"
output: html_document
---

```{r}
rm(list = ls())
```

```{r}
wd <- "/Users/gabriele.minniti/Desktop/università/Data_Mining_Solari/Progetti_Solari/Wine"
setwd(wd)
```

```{r}
library(doMC)
detectCores()
registerDoMC(cores = 3)
```
```{r}
library(data.table)
library(mlr)
```
#load data
```{r}
train <- read.csv("official_train.csv", header = TRUE)
train$X.1 <- NULL
train$X <- NULL
test <- read.csv("official_test.csv", header = TRUE)
head(test)
test$X <- NULL
test$X.1 <- NULL
```
#convert data frame to data table
```{r}
setDT(train)
setDT(test)
```
#check missing values 

```{r}
table(is.na(train))
sapply(train, function(x) sum(is.na(x))/length(x))*100

```

```{r}
table(is.na(test))
sapply(test, function(x) sum(is.na(x))/length(x))*100
```
#quick data cleaning
#remove extra character from target variable
```{r}
library(stringr)

#test [,target := substr(target,start = 1,stop = nchar(target)-1)]
```
```{r}
labels <- train$good
ts_label <- test$good

new_tr <- model.matrix(~.+0,data = train[,-c("good"),with=F]) 
new_ts <- model.matrix(~.+0,data = test[,-c("good"),with=F])
```

```{r}
labels <- c()
for(i in 1:length(train$good)){
  if (train$good[i]=="Good"){
    labels[i]=1
  }
  else{
    labels[i]=0
  }
}

ts_label <- c()
for (i in 1:length(test$good)){
  if(test$good[i]=="Good"){
    ts_label[i] = 1
  }
  else{
    ts_label[i] = 0
  }
}
```

#convert factor to numeric 
```{r}
labels <- as.numeric(labels)-1
ts_label <- as.numeric(ts_label)-1
```

#preparing matrix 
```{r}
dtrain <- xgb.DMatrix(data = new_tr,label = labels) 
dtest <- xgb.DMatrix(data = new_ts,label=ts_label)
```
#default parameters
```{r}
params <- list(booster = "gbtree", objective = "binary:logistic", eta=0.3, gamma=0, max_depth=6, min_child_weight=1, subsample=1, colsample_bytree=1)
```

```{r}
xgbcv <- xgb.cv( params = params, data = dtrain, nrounds = 200, nfold = 5, showsd = T, stratified = T, print_every_n = 10, early_stop_round = 20, maximize = F)
```

```{r}
min(xgbcv$test.error.mean)
```

```{r}
xgb1 <- xgb.train (params = params, data = dtrain, nrounds = 79, watchlist = list(val=dtest,train=dtrain), print_every_n = 10, early_stop_round = 10, maximize = F , eval_metric = "error")
```
#model prediction
```{r}
xgbpred <- predict (xgb1,dtest)
xgbpred <- ifelse (xgbpred > 0.5,1,0)
```

```{r}
score <- function(pred, truth, name="model") {
  ctable <- table(truth=truth,
                  pred=pred)
  accuracy <- round(sum(diag(ctable))/sum(ctable), 3)
  specificity <- round(ctable[1,1]/sum(ctable[1,]),3)
  data.frame(model=name, accuracy=accuracy, specificity=specificity)
}
```


```{r}
score(xgbpred, test$good, "xgcazzoboost")
```

